const COLLECTIONS_KEY='kelo-collections-ledger-v1';
const $c=(s,r=document)=>r.querySelector(s);
const moneyC=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n||0));
const dateOffset=(days=0)=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};

function seedCollections(){return {debts:[
  {id:'d1',customer:'Carlos',business:'watches',item:'Daytona Black',originalAmount:200,paid:100,balance:100,originalDueDate:dateOffset(0),currentDueDate:dateOffset(0),promiseCount:1,brokenPromises:0,status:'open',payments:[{amount:100,date:dateOffset(-2)}],history:[{type:'created',date:dateOffset(-2),text:'Venta fiada: $100 ahora / $100 pendiente'}]},
  {id:'d2',customer:'Juan',business:'moissanite',item:'Tennis Chain',originalAmount:350,paid:150,balance:200,originalDueDate:dateOffset(-4),currentDueDate:dateOffset(-4),promiseCount:2,brokenPromises:1,status:'overdue',payments:[{amount:150,date:dateOffset(-9)}],history:[{type:'promise_broken',date:dateOffset(-4),text:'No pagó en la fecha prometida'}]},
  {id:'d3',customer:'Maria',business:'zara',item:'Wholesale lot',originalAmount:498,paid:0,balance:498,originalDueDate:dateOffset(3),currentDueDate:dateOffset(3),promiseCount:1,brokenPromises:0,status:'open',payments:[],history:[]}
]}}
function loadCollections(){try{return {...seedCollections(),...(JSON.parse(localStorage.getItem(COLLECTIONS_KEY)||'null')||{})}}catch{return seedCollections()}}
let collections=loadCollections();
function saveCollections(){localStorage.setItem(COLLECTIONS_KEY,JSON.stringify(collections))}
function refreshDebtStatus(){const today=new Date();today.setHours(0,0,0,0);collections.debts.forEach(d=>{if(['paid','written_off'].includes(d.status))return;const due=new Date(d.currentDueDate+'T00:00:00');d.status=due<today?'overdue':'open'});saveCollections()}
function totals(){refreshDebtStatus();const open=collections.debts.filter(d=>!['paid','written_off'].includes(d.status));const week=new Date();week.setDate(week.getDate()+7);return {all:open.reduce((n,d)=>n+d.balance,0),overdue:open.filter(d=>d.status==='overdue').reduce((n,d)=>n+d.balance,0),today:open.filter(d=>d.currentDueDate===dateOffset(0)).reduce((n,d)=>n+d.balance,0),next7:open.filter(d=>{const x=new Date(d.currentDueDate+'T00:00:00');return x>new Date()&&x<=week}).reduce((n,d)=>n+d.balance,0)}}
function facts(d){return [`Pagado ${moneyC(d.paid)} de ${moneyC(d.originalAmount)}`,`Promesas ${d.promiseCount}`,`Promesas incumplidas ${d.brokenPromises}`,`Fecha original ${d.originalDueDate}`,`Fecha actual ${d.currentDueDate}`]}
function debtCard(d){const overdue=d.status==='overdue';return `<article class="op-card" data-debt-card="${d.id}"><div class="op-card-head"><div><small>${overdue?'🔴 OVERDUE':'💰 RECEIVABLE'} · ${d.business.toUpperCase()}</small><h3>${d.customer} · ${d.item}</h3></div><strong class="${overdue?'money-due':''}">${moneyC(d.balance)}</strong></div><p>${facts(d).join(' · ')}</p><div class="inline-actions"><button class="primary" data-debt-paid="${d.id}">PAID</button><button class="secondary" data-debt-remind="${d.id}">REMIND</button><button class="secondary" data-debt-reschedule="${d.id}">RESCHEDULE</button></div></article>`}
function renderCollections(){const host=$c('#collectionsLedger');if(!host)return;const t=totals();const rows=collections.debts.filter(d=>!['paid','written_off'].includes(d.status)).sort((a,b)=>a.status===b.status?new Date(a.currentDueDate)-new Date(b.currentDueDate):a.status==='overdue'?-1:1);host.innerHTML=`<div class="view-head" style="margin-top:14px"><h2>Fiado / Por cobrar</h2><p>La deuda no desaparece al cambiar la fecha. Kelo conserva la fecha original, pagos y promesas.</p></div><div class="kpi-grid"><div class="kpi"><small>Vencido</small><strong class="money-due">${moneyC(t.overdue)}</strong></div><div class="kpi"><small>Vence hoy</small><strong>${moneyC(t.today)}</strong></div><div class="kpi"><small>Próx. 7 días</small><strong>${moneyC(t.next7)}</strong></div><div class="kpi"><small>Total abierto</small><strong>${moneyC(t.all)}</strong></div></div><div class="stack">${rows.map(debtCard).join('')||'<div class="op-card">No hay deuda abierta.</div>'}</div>`}
function markPaid(id){const d=collections.debts.find(x=>x.id===id);if(!d)return;d.payments.push({amount:d.balance,date:dateOffset(0)});d.paid+=d.balance;d.balance=0;d.status='paid';d.history.push({type:'paid',date:dateOffset(0),text:'Saldo pagado'});saveCollections();renderCollections()}
function reschedule(id){const d=collections.debts.find(x=>x.id===id);if(!d)return;const next=prompt('Nueva fecha de pago (YYYY-MM-DD)',dateOffset(2));if(!next)return;if(d.status==='overdue')d.brokenPromises+=1;d.promiseCount+=1;d.currentDueDate=next;d.status='open';d.history.push({type:'rescheduled',date:dateOffset(0),text:`Reagendado para ${next}`});saveCollections();renderCollections()}
function remind(id){const d=collections.debts.find(x=>x.id===id);if(!d)return;const toast=$c('#operatorToast');if(toast){toast.textContent=`Cobro preparado: ${d.customer} · ${moneyC(d.balance)}`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2000)}}
function appendCollectionsToForget(){setTimeout(()=>{const target=$c('#forgetItems');if(!target)return;collections.debts.filter(d=>d.status==='overdue'||d.currentDueDate===dateOffset(0)).forEach(d=>{if(target.querySelector(`[data-collection-forget="${d.id}"]`))return;target.insertAdjacentHTML('afterbegin',`<div class="forget-row" data-collection-forget="${d.id}"><span>${d.status==='overdue'?'🔴':'💰'} ${d.customer}: ${moneyC(d.balance)} ${d.status==='overdue'?'vencido':'vence hoy'}</span><button class="secondary" data-debt-remind="${d.id}">COLLECT</button></div>`)});},0)}
document.addEventListener('click',e=>{const p=e.target.closest('[data-debt-paid]');if(p)markPaid(p.dataset.debtPaid);const r=e.target.closest('[data-debt-remind]');if(r)remind(r.dataset.debtRemind);const s=e.target.closest('[data-debt-reschedule]');if(s)reschedule(s.dataset.debtReschedule)});
$c('#forgetScan')?.addEventListener('click',appendCollectionsToForget);
renderCollections();