const CORE_KEY='kelo-associates-v2';
const OP_KEY='kelo-operator-v1';
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n||0));
const uid=(p='id')=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
let toastTimer;

function loadCore(){try{return JSON.parse(localStorage.getItem(CORE_KEY)||'null')||{clients:[],conversations:[],messages:[],tasks:[],sales:[]}}catch{return {clients:[],conversations:[],messages:[],tasks:[],sales:[]}}}
function seedOperator(){return {filter:'all',tasks:[{id:'ot1',title:'Comprar Daytona negro para Juan',business:'watches',customer:'Juan',type:'purchase',dueText:'Viernes 3:00 PM',done:false},{id:'ot2',title:'Llamar a Maria para confirmar entrega',business:'zara',customer:'Maria',type:'call',dueText:'Mañana 11:00 AM',done:false},{id:'ot3',title:'Cobrar depósito a Kevin',business:'moissanite',customer:'Kevin',type:'collect',dueText:'Hoy 6:00 PM',done:false}],orders:[{id:'KO-1001',business:'watches',customer:'Luis',item:'Daytona Black',total:200,paid:0,status:'reserved'},{id:'KO-1002',business:'zara',customer:'Maria',item:'34 prendas mixtas',total:646,paid:285,status:'reserved'},{id:'KO-1003',business:'moissanite',customer:'Kevin',item:'Cuban Chain 12mm',total:850,paid:150,status:'reserved'}],products:[{id:'p1',business:'watches',name:'Daytona Black',stock:2,reserved:1,asks7d:9,price:200,reorderAt:3},{id:'p2',business:'zara',name:'Inventario Zara mixto',stock:78,reserved:34,asks7d:12,price:19,reorderAt:30},{id:'p3',business:'moissanite',name:'Cuban Chain 12mm',stock:1,reserved:1,asks7d:4,price:850,reorderAt:2}],promises:[{id:'pr1',customer:'Luis',business:'watches',text:'Confirmar hora de delivery hoy',resolved:false},{id:'pr2',customer:'Maria',business:'zara',text:'Enviar fotos de stock hoy',resolved:false}],manualChats:[{id:'mc1',business:'watches',name:'Luis',product:'Daytona Black',heat:96,summary:'Aceptó $200 · sin caja · Manhattan · quiere delivery hoy',signals:['precio aceptado','ubicación','hoy','delivery']},{id:'mc2',business:'zara',name:'Maria',product:'34 prendas',heat:91,summary:'Mayorista · NJ · quiere tallas mixtas y fotos antes del depósito',signals:['cantidad alta','delivery','precio mayorista']},{id:'mc3',business:'moissanite',name:'Kevin',product:'Cuban Chain 12mm',heat:89,summary:'Budget $700–$900 · pide video con tester · pickup sábado',signals:['budget','prueba','pickup']}],alerted:{}}}
function loadOperator(){try{return {...seedOperator(),...(JSON.parse(localStorage.getItem(OP_KEY)||'null')||{})}}catch{return seedOperator()}}
let op=loadOperator();
function save(){localStorage.setItem(OP_KEY,JSON.stringify(op))}
function toast(text){const e=$('#operatorToast');e.textContent=text;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),2000)}
function bizOk(b){return op.filter==='all'||b===op.filter}

function heatFromCore(conv,client){let score=0,reasons=[];const text=(conv?.lastMessage||'').toLowerCase();const interest=(client?.interests||[]).join(' ').toLowerCase();if(interest){score+=18;reasons.push('producto definido')}if(/precio|\$|cu[aá]nto|price/.test(text)){score+=18;reasons.push('precio')}if(/hoy|today|ahora|now|mañana|tomorrow/.test(text)){score+=20;reasons.push('timing')}if(/delivery|entrega|pickup|recoger|ubicaci[oó]n|bronx|queens|manhattan|nj/.test(text)){score+=18;reasons.push('logística')}if(/quiero|lo llevo|perfecto|nos vemos|comprar|buy/.test(text)){score+=22;reasons.push('intención')}if(conv?.unread>0){score+=4}return {score:Math.min(score,100),reasons}}
function coreChats(){const core=loadCore();return (core.conversations||[]).map(c=>{const client=(core.clients||[]).find(x=>x.id===c.clientId)||{};const h=heatFromCore(c,client);return {id:c.id,business:'watches',name:client.name||'Cliente',product:(client.interests||[])[0]||'Reloj',heat:Math.max(h.score,c.leadTemp==='hot'?78:c.leadTemp==='warm'?52:25),summary:c.lastMessage||'',signals:h.reasons,core:true}})}
function allChats(){const core=coreChats();const names=new Set(core.map(x=>x.name));return [...core,...op.manualChats.filter(x=>!names.has(x.name))]}
function filtered(arr){return arr.filter(x=>bizOk(x.business))}

function render(){renderToday();renderChats();renderOrders();renderProducts();renderMoney();scanHot(false)}
function renderToday(){const chats=filtered(allChats()),orders=filtered(op.orders),products=filtered(op.products),tasks=filtered(op.tasks).filter(t=>!t.done);const hot=chats.filter(c=>c.heat>=75);const due=orders.reduce((n,o)=>n+Math.max(0,o.total-o.paid),0);$('#todayKpis').innerHTML=[[hot.length,'HOT leads'],[money(due),'Por cobrar'],[tasks.length,'Tareas abiertas'],[products.filter(p=>p.stock<=p.reorderAt).length,'Comprar stock']].map(([v,l])=>`<div class="kpi"><small>${l}</small><strong>${v}</strong></div>`).join('');const actions=[];hot.slice(0,4).forEach(c=>actions.push(`<article class="op-card"><div class="op-card-head"><div><small>🔥 CLOSE NOW · ${c.business.toUpperCase()}</small><h3>${c.name} · ${c.product}</h3></div><span class="heat-pill">${c.heat}%</span></div><div class="heat-track"><i style="width:${c.heat}%"></i></div><p>${c.summary}</p><div class="inline-actions"><button class="primary" data-open-hot="${c.id}">TAKE OVER</button><button class="secondary" data-remind-name="${c.name}">REMIND ME</button></div></article>`));orders.filter(o=>o.total>o.paid).slice(0,2).forEach(o=>actions.push(`<article class="op-card"><div class="op-card-head"><div><small>💵 COLLECT · ${o.business.toUpperCase()}</small><h3>${o.customer}</h3></div><span class="status-pill">${money(o.total-o.paid)} due</span></div><p>${o.item} · ${o.status}</p><div class="inline-actions"><button class="primary" data-collect="${o.id}">COLLECT</button></div></article>`));products.filter(p=>p.stock<=p.reorderAt).slice(0,2).forEach(p=>actions.push(`<article class="op-card"><div class="op-card-head"><div><small>📦 BUY · ${p.business.toUpperCase()}</small><h3>${p.name}</h3></div><span class="status-pill">${p.stock} left</span></div><p>${p.asks7d} personas preguntaron en 7 días · ${p.reserved} reservado.</p><div class="inline-actions"><button class="primary" data-buy="${p.id}">CREATE BUY TASK</button></div></article>`));$('#todayActions').innerHTML=actions.join('')||'<div class="op-card"><p>Nada urgente con este filtro.</p></div>';$('#attentionTitle').textContent=`${actions.length} cosas necesitan tu atención.`}
function renderChats(){const rows=filtered(allChats()).sort((a,b)=>b.heat-a.heat);$('#chatCards').innerHTML=rows.map(c=>`<article class="op-card"><div class="op-card-head"><div><h3>${c.name}</h3><p>${c.business.toUpperCase()} · ${c.product}</p></div><span class="heat-pill">${c.heat}%</span></div><div class="heat-track"><i style="width:${c.heat}%"></i></div><p>${c.summary}</p><p><small>${(c.signals||[]).map(x=>'✓ '+x).join(' · ')}</small></p><div class="inline-actions"><button class="primary" data-open-hot="${c.id}">${c.heat>=75?'TAKE OVER':'OPEN'}</button><button class="secondary" data-remind-name="${c.name}">REMIND ME</button></div></article>`).join('')||'<div class="op-card">No chats.</div>'}
function renderOrders(){const flow=['reserved','paid','ready','delivery','delivered'];$('#orderCards').innerHTML=filtered(op.orders).map(o=>`<article class="op-card"><div class="op-card-head"><div><h3>${o.customer} · ${o.item}</h3><p>${o.business.toUpperCase()} · ${o.id}</p></div><span class="status-pill">${o.status.toUpperCase()}</span></div><p>Total ${money(o.total)} · Paid ${money(o.paid)} · Balance <b>${money(o.total-o.paid)}</b></p><div class="inline-actions"><button class="primary" data-order-next="${o.id}">ADVANCE</button>${o.total>o.paid?`<button class="secondary" data-collect="${o.id}">COLLECT</button>`:''}</div></article>`).join('')||'<div class="op-card">No orders.</div>'}
function renderProducts(){$('#productCards').innerHTML=filtered(op.products).map(p=>`<article class="op-card"><div class="op-card-head"><div><h3>${p.name}</h3><p>${p.business.toUpperCase()}</p></div><span class="status-pill">${p.stock} stock</span></div><p>${p.asks7d} asks / 7d · ${p.reserved} reserved · ${money(p.price)} sale price</p><div class="inline-actions">${p.stock<=p.reorderAt?`<button class="primary" data-buy="${p.id}">CREATE BUY TASK</button>`:'<button class="secondary" disabled>STOCK OK</button>'}</div></article>`).join('')||'<div class="op-card">No products.</div>'}
function renderMoney(){const orders=filtered(op.orders),due=orders.reduce((n,o)=>n+Math.max(0,o.total-o.paid),0),collected=orders.reduce((n,o)=>n+o.paid,0),sales=loadCore().sales||[];$('#moneyKpis').innerHTML=[[money(collected),'Collected'],[money(due),'Pending'],[orders.length,'Open orders'],[money(sales.reduce((n,s)=>n+s.amount,0)),'Core sales']].map(([v,l])=>`<div class="kpi"><small>${l}</small><strong>${v}</strong></div>`).join('');$('#moneyCards').innerHTML=orders.filter(o=>o.total>o.paid).map(o=>`<article class="op-card"><div class="op-card-head"><div><h3>${o.customer}</h3><p>${o.item}</p></div><strong class="money-due">${money(o.total-o.paid)}</strong></div><div class="inline-actions"><button class="primary" data-collect="${o.id}">COLLECT</button><button class="secondary" data-remind-name="${o.customer}">REMIND ME</button></div></article>`).join('')||'<div class="op-card">Nada pendiente.</div>'}

function parseTask(text){const l=text.toLowerCase();let type='task',business=op.filter==='all'?'general':op.filter;if(l.includes('comprar'))type='purchase';else if(l.includes('llamar')||l.includes('confirmar'))type='call';else if(l.includes('cobrar'))type='collect';else if(l.includes('entregar'))type='delivery';if(/daytona|reloj|submariner|datejust/.test(l))business='watches';if(/zara|ropa|prenda/.test(l))business='zara';if(/moissan|cadena|cuban|joya/.test(l))business='moissanite';const m=text.match(/para\s+([A-Za-zÁÉÍÓÚÑáéíóúñ]+)/);return {id:uid('task'),title:text,business,customer:m?.[1]||'',type,dueText:'Programada desde texto',done:false}}
function createQuickTask(){const i=$('#quickTaskInput'),text=i.value.trim();if(!text)return toast('Escribe una tarea');op.tasks.unshift(parseTask(text));save();i.value='';toast('Tarea creada + alerta preparada');render()}
function forgetItems(){const rows=[];filtered(allChats()).filter(c=>c.heat>=85).forEach(c=>rows.push(`🔥 ${c.name}: ${c.heat}% HOT — ${c.summary}`));filtered(op.orders).filter(o=>o.total>o.paid).forEach(o=>rows.push(`💵 ${o.customer}: ${money(o.total-o.paid)} pendiente`));filtered(op.products).filter(p=>p.stock<=p.reorderAt).forEach(p=>rows.push(`📦 ${p.name}: ${p.stock} left con ${p.asks7d} asks recientes`));filtered(op.promises).filter(p=>!p.resolved).forEach(p=>rows.push(`🤝 ${p.customer}: ${p.text}`));filtered(op.tasks).filter(t=>!t.done).slice(0,4).forEach(t=>rows.push(`⏰ ${t.title} — ${t.dueText}`));return rows}
function runForgetScan(){const rows=forgetItems(),panel=$('#forgetPanel');$('#forgetItems').innerHTML=rows.slice(0,10).map(x=>`<div class="forget-row"><span>${x}</span><button class="secondary">OPEN</button></div>`).join('')||'<p>Nada importante detectado.</p>';panel.hidden=false;panel.scrollIntoView({behavior:'smooth',block:'nearest'});toast(`${rows.length} items encontrados`)}
function scanHot(show=true){const hot=filtered(allChats()).filter(c=>c.heat>=90&&!op.alerted[c.id]);if(!hot.length)return;const c=hot[0];op.alerted[c.id]=Date.now();save();if(show){$('#hotAlertTitle').textContent=`${c.name} · ${c.heat}%`;$('#hotAlertText').textContent=`${c.product} — ${c.summary}`;$('#hotAlert').hidden=false}}

$('#addQuickTask').addEventListener('click',createQuickTask);$('#quickTaskInput').addEventListener('keydown',e=>{if(e.key==='Enter')createQuickTask()});$('#forgetScan').addEventListener('click',runForgetScan);$('#hotAlertClose').addEventListener('click',()=>$('#hotAlert').hidden=true);$('#hotAlertOpen').addEventListener('click',()=>{$('#hotAlert').hidden=true;document.querySelector('[data-view="chats"]').click()});
$$('[data-business]').forEach(b=>b.addEventListener('click',()=>{$$('[data-business]').forEach(x=>x.classList.remove('active'));b.classList.add('active');op.filter=b.dataset.business;save();render()}));
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>{$$('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('[data-view-panel]').forEach(p=>p.classList.toggle('active',p.dataset.viewPanel===b.dataset.view))}));
document.addEventListener('click',e=>{const remind=e.target.closest('[data-remind-name]');if(remind){$('#quickTaskInput').value=`Follow-up con ${remind.dataset.remindName} mañana a las 11 AM`;$('#quickTaskInput').focus()}const buy=e.target.closest('[data-buy]');if(buy){const p=op.products.find(x=>x.id===buy.dataset.buy);$('#quickTaskInput').value=`Comprar ${p.name} para reponer inventario mañana a las 11 AM`;$('#quickTaskInput').focus()}const collect=e.target.closest('[data-collect]');if(collect){const o=op.orders.find(x=>x.id===collect.dataset.collect);toast(`Recordatorio de cobro preparado para ${o.customer}`)}const next=e.target.closest('[data-order-next]');if(next){const o=op.orders.find(x=>x.id===next.dataset.orderNext),flow=['reserved','paid','ready','delivery','delivered'];o.status=flow[Math.min(flow.indexOf(o.status)+1,flow.length-1)];save();render();toast('Order → '+o.status.toUpperCase())}const hot=e.target.closest('[data-open-hot]');if(hot)toast('Human takeover ready — integración WhatsApp real pendiente backend')});

render();setTimeout(()=>scanHot(true),700);