import './updater.js';
const ORG_KEY='kelo-organizer-v1';
const CRM_KEY='kelo-associates-v2';
const ICONS={call:'☎',visit:'⌖',task:'✓',followup:'↻'};
const LABELS={call:'Llamada',visit:'Visita',task:'Tarea',followup:'Follow-up'};
const qs=(s,r=document)=>r.querySelector(s);
const qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=()=>`org_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
const pad=n=>String(n).padStart(2,'0');
const localDay=d=>{d=new Date(d);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const fmtTime=d=>new Date(d).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});
const fmtDate=d=>new Date(d).toLocaleDateString('es-US',{weekday:'short',month:'short',day:'numeric'});
function load(){try{return JSON.parse(localStorage.getItem(ORG_KEY))||{version:1,items:[]}}catch{return{version:1,items:[]}}}
let org=load();
function save(){localStorage.setItem(ORG_KEY,JSON.stringify(org));renderAll()}
function crm(){try{return JSON.parse(localStorage.getItem(CRM_KEY))||{clients:[]}}catch{return{clients:[]}}}
function getClient(id){return crm().clients?.find(c=>c.id===id)}
function now(){return new Date()}
function upcoming(){return org.items.filter(x=>!x.done).sort((a,b)=>new Date(a.dueAt)-new Date(b.dueAt))}
function dueToday(){const d=localDay(now());return upcoming().filter(x=>localDay(x.dueAt)===d)}
function overdue(){return upcoming().filter(x=>new Date(x.dueAt)<now())}
function withinHours(h){const n=now(),limit=new Date(n.getTime()+h*3600000);return upcoming().filter(x=>new Date(x.dueAt)>=n&&new Date(x.dueAt)<=limit)}
function reminderOffsets(item){return (item.reminders||[]).map(Number).filter(Number.isFinite).sort((a,b)=>b-a)}
function nextReminderText(item){const due=new Date(item.dueAt),n=now();const candidates=reminderOffsets(item).map(m=>new Date(due.getTime()-m*60000)).filter(t=>t>=n).sort((a,b)=>a-b);return candidates[0]?`Próximo aviso ${fmtTime(candidates[0])}`:'Sin avisos futuros'}
function typeDefaults(type){if(type==='call')return{title:'Llamar cliente',reminders:[15,0]};if(type==='visit')return{title:'Visita con cliente',reminders:[1440,60,30,0]};if(type==='followup')return{title:'Dar seguimiento',reminders:[60,0]};return{title:'Completar tarea',reminders:[60,0]}}
function itemClass(item){const d=new Date(item.dueAt),n=now();if(d<n)return'overdue';if(d-n<=3600000)return'soon';return''}
function itemHTML(item){const c=getClient(item.clientId);const client=c?.name||item.clientName||'General';const phone=c?.phone||item.phone||'';const actions=[];if(item.type==='call'&&phone)actions.push(`<a class="smart-mini call" href="tel:${safe(phone)}">Llamar</a>`);actions.push(`<button class="smart-mini done" data-org-done="${item.id}">Hecho</button>`);actions.push(`<button class="smart-mini" data-org-snooze="${item.id}">+30 min</button>`);return `<div class="smart-item ${itemClass(item)}"><div class="smart-icon">${ICONS[item.type]||'✓'}</div><div><h4>${safe(item.title)}</h4><p>${safe(LABELS[item.type]||'Tarea')} · ${safe(client)}${item.location?` · ${safe(item.location)}`:''}<br>${safe(nextReminderText(item))}</p><div class="smart-row-actions">${actions.join('')}</div></div><time datetime="${safe(item.dueAt)}">${fmtDate(item.dueAt)}<br>${fmtTime(item.dueAt)}</time></div>`}
function plannerHTML(){const today=dueToday(),late=overdue(),calls=upcoming().filter(x=>x.type==='call');return `<div class="card smart-planner" id="smartPlannerCard"><div class="smart-head"><div><h3>Organizador inteligente</h3><p>Llamadas, visitas y tareas que no debes olvidar.</p></div><button class="iconbtn" id="openOrganizer" aria-label="Agregar acción">＋</button></div><div class="smart-summary"><div class="smart-stat"><strong>${today.length}</strong><span>Hoy</span></div><div class="smart-stat"><strong>${late.length}</strong><span>Vencidas</span></div><div class="smart-stat"><strong>${calls.length}</strong><span>Llamadas</span></div></div><div id="smartTodayList" class="smart-list">${today.length?today.slice(0,5).map(itemHTML).join(''):'<div class="empty">No tienes acciones programadas para hoy.</div>'}</div></div>`}
function organizerScreenHTML(){const rows=upcoming();return `<div class="card smart-planner" id="smartOrganizerPanel"><div class="smart-head"><div><h3>Agenda automática</h3><p>Todo lo que requiere una acción tuya.</p></div><button class="primary" id="openOrganizer2">Nueva</button></div><div class="smart-actions"><button class="smart-chip" data-org-filter="all">Todo</button><button class="smart-chip" data-org-filter="call">Llamadas</button><button class="smart-chip" data-org-filter="visit">Visitas</button><button class="smart-chip" data-org-filter="task">Tareas</button><button class="smart-chip" data-org-filter="followup">Follow-up</button></div><div id="smartAllList" class="smart-list">${rows.length?rows.map(itemHTML).join(''):'<div class="empty">No hay acciones pendientes.</div>'}</div></div>`}
function sheetHTML(){return `<div class="sheetback" id="organizerSheet" role="dialog" aria-modal="true" aria-label="Nueva acción"><div class="sheet"><div class="handle"></div><div class="sheethead"><div><h3>Nueva acción</h3><p class="muted">Kelo Associates te recordará lo importante.</p></div><button class="iconbtn" data-org-close aria-label="Cerrar">×</button></div><form id="organizerForm" class="smart-form"><div class="smart-type-grid"><button type="button" class="smart-type" data-org-type="call"><span>☎</span><span>Llamada</span></button><button type="button" class="smart-type" data-org-type="visit"><span>⌖</span><span>Visita</span></button><button type="button" class="smart-type" data-org-type="task"><span>✓</span><span>Tarea</span></button></div><input type="hidden" name="type" value="task"><div class="field"><label>Qué debes hacer</label><input name="title" required placeholder="Ej. Llevar Daytona negro"></div><div class="field"><label>Cliente</label><select name="clientId" id="organizerClient"><option value="">General / sin cliente</option></select></div><div class="split"><div class="field"><label>Fecha</label><input name="date" type="date" required></div><div class="field"><label>Hora</label><input name="time" type="time" required></div></div><div class="field"><label>Lugar</label><input name="location" placeholder="Dirección o punto de encuentro"></div><div class="field"><label>Notas</label><textarea name="notes" placeholder="Qué llevar, qué preguntar, detalles importantes"></textarea></div><div class="field"><label>Avisarme</label><div class="smart-reminders"><label class="smart-reminder-option"><input type="checkbox" name="reminder" value="1440"><span>1 día antes</span></label><label class="smart-reminder-option"><input type="checkbox" name="reminder" value="60"><span>1 hora antes</span></label><label class="smart-reminder-option"><input type="checkbox" name="reminder" value="30"><span>30 min</span></label><label class="smart-reminder-option"><input type="checkbox" name="reminder" value="15"><span>15 min</span></label><label class="smart-reminder-option"><input type="checkbox" name="reminder" value="0" checked><span>A la hora</span></label></div></div><div class="field"><label>Prioridad</label><select name="priority"><option value="high">Alta</option><option value="medium" selected>Media</option><option value="low">Baja</option></select></div><button class="primary wide" type="submit">Guardar y programar avisos</button></form></div></div>`}
function populateClients(){const sel=qs('#organizerClient');if(!sel)return;const current=sel.value;const clients=crm().clients||[];sel.innerHTML='<option value="">General / sin cliente</option>'+clients.map(c=>`<option value="${safe(c.id)}">${safe(c.name)}${c.phone?' — '+safe(c.phone):''}</option>`).join('');sel.value=current}
function setFormType(type){const f=qs('#organizerForm');if(!f)return;f.elements.type.value=type;qsa('[data-org-type]',f).forEach(b=>b.classList.toggle('primary',b.dataset.orgType===type));const defaults=typeDefaults(type);if(!f.elements.title.value||Object.values(LABELS).some(v=>f.elements.title.value.includes(v)))f.elements.title.value=defaults.title;qsa('input[name="reminder"]',f).forEach(x=>x.checked=defaults.reminders.includes(Number(x.value)))}
function openForm(type='task'){populateClients();const f=qs('#organizerForm');if(!f)return;f.reset();const d=new Date(Date.now()+60*60000);f.elements.date.value=localDay(d);f.elements.time.value=`${pad(d.getHours())}:${pad(d.getMinutes())}`;setFormType(type);qs('#organizerSheet').classList.add('open')}
function closeForm(){qs('#organizerSheet')?.classList.remove('open')}
function notify(title,body){if('Notification'in window&&Notification.permission==='granted'){try{new Notification(title,{body,icon:'icon.svg',tag:'kelo-organizer'});return true}catch{}}return false}
function checkReminders(){const n=Date.now();let changed=false;upcoming().forEach(item=>{const due=new Date(item.dueAt).getTime();item.sentReminders=item.sentReminders||[];reminderOffsets(item).forEach(offset=>{const fire=due-offset*60000;const key=String(offset);if(n>=fire&&n<fire+60000&&!item.sentReminders.includes(key)){const c=getClient(item.clientId);notify(`${ICONS[item.type]||'✓'} ${item.title}`,`${c?.name||'General'} · ${fmtTime(item.dueAt)}${item.location?' · '+item.location:''}`);item.sentReminders.push(key);changed=true}})});if(changed){localStorage.setItem(ORG_KEY,JSON.stringify(org));renderAll()}}
function renderAll(){const todayHost=qs('#smartTodayHost');if(todayHost)todayHost.innerHTML=plannerHTML();const all=qs('#smartOrganizerHost');if(all)all.innerHTML=organizerScreenHTML()}
function mount(){
  const today=qs('[data-screen="today"] .hero');if(today&&!qs('#smartTodayHost')){const host=document.createElement('div');host.id='smartTodayHost';today.insertAdjacentElement('afterend',host)}
  const rem=qs('[data-screen="reminders"] .screenhead');if(rem&&!qs('#smartOrganizerHost')){const host=document.createElement('div');host.id='smartOrganizerHost';rem.insertAdjacentElement('afterend',host)}
  if(!qs('#organizerSheet'))document.body.insertAdjacentHTML('beforeend',sheetHTML());
  renderAll();populateClients();
}
document.addEventListener('click',e=>{const open=e.target.closest('#openOrganizer,#openOrganizer2');if(open){openForm();return}const type=e.target.closest('[data-org-type]');if(type){setFormType(type.dataset.orgType);return}if(e.target.closest('[data-org-close]')){closeForm();return}const done=e.target.closest('[data-org-done]');if(done){const item=org.items.find(x=>x.id===done.dataset.orgDone);if(item){item.done=true;item.completedAt=new Date().toISOString();save()}return}const snooze=e.target.closest('[data-org-snooze]');if(snooze){const item=org.items.find(x=>x.id===snooze.dataset.orgSnooze);if(item){item.dueAt=new Date(Date.now()+30*60000).toISOString();item.sentReminders=[];save()}return}const filter=e.target.closest('[data-org-filter]');if(filter){const type=filter.dataset.orgFilter;const rows=upcoming().filter(x=>type==='all'||x.type===type);const list=qs('#smartAllList');if(list)list.innerHTML=rows.length?rows.map(itemHTML).join(''):'<div class="empty">No hay acciones aquí.</div>';qsa('[data-org-filter]').forEach(b=>b.classList.toggle('primary',b===filter));return}});
document.addEventListener('submit',e=>{if(e.target.id!=='organizerForm')return;e.preventDefault();const f=new FormData(e.target);const type=String(f.get('type')||'task');const dueAt=new Date(`${f.get('date')}T${f.get('time')}:00`).toISOString();const clientId=String(f.get('clientId')||'');const client=getClient(clientId);const reminders=f.getAll('reminder').map(Number);org.items.push({id:uid(),type,title:String(f.get('title')).trim(),clientId:clientId||null,clientName:client?.name||'',phone:client?.phone||'',dueAt,location:String(f.get('location')||'').trim(),notes:String(f.get('notes')||'').trim(),priority:String(f.get('priority')||'medium'),reminders,done:false,sentReminders:[],createdAt:new Date().toISOString()});localStorage.setItem(ORG_KEY,JSON.stringify(org));closeForm();renderAll();if('Notification'in window&&Notification.permission==='default')Notification.requestPermission().catch(()=>{});});
window.addEventListener('storage',e=>{if(e.key===CRM_KEY||e.key===ORG_KEY){org=load();renderAll();populateClients()}});
function boot(){mount();checkReminders();setInterval(checkReminders,30000);setInterval(()=>{populateClients();renderAll()},60000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();